package edu.cmu.sei.atm.ui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiplayScreen.java
 *
 * Created on May 5, 2010, 2:47:33 PM
 */

/**
 *
 * @author hadj
 */
public class Screen extends javax.swing.JPanel {

    /** Creates new form DiplayScreen */
    public Screen() {
        initComponents();
        initComponentsExtra();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabelImageScreen = new javax.swing.JLabel();
        jScrollPaneScreen = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(605, 398));
        setLayout(null);

        jLabelImageScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageScreen.setLabelFor(this);
        add(jLabelImageScreen);
        jLabelImageScreen.setBounds(290, 170, 160, 210);

        this.setOpaque(false);
        screen.setBackground(java.awt.Color.GRAY);
        screen.setEditable(false);
        screen.setFont(new java.awt.Font("Nimbus Sans L", 0, 28)); // NOI18N
        screen.setForeground(new java.awt.Color(170, 253, 171));
        screen.setMargin(new java.awt.Insets(10, 20, 10, 20));
        screen.setColumns(20);
        screen.setRows(5);
        jScrollPaneScreen.setViewportView(screen);

        add(jScrollPaneScreen);
        jScrollPaneScreen.setBounds(0, 0, 605, 398);
    }// </editor-fold>

    public void initComponentsExtra()
    {
        jLabelImageScreen.setVisible(false);
    }
    // Variables declaration - do not modify
    private javax.swing.JLabel jLabelImageScreen;
    private javax.swing.JScrollPane jScrollPaneScreen;
    private javax.swing.JTextArea screen;
    // End of variables declaration


   // displays a message without a carriage return
   public void displayMessage( String message )
   {
       screen.append(message);
      //System.out.print( message );
   } // end method displayMessage

   // display a message with a carriage return
   public void displayMessageLine( String message )
   {
       screen.append(message+"\n");
      //System.out.println( message );
   } // end method displayMessageLine

   public void clearMessageScreen()
   {
       screen.setText("");

   } // end method displayMessageLine

   public void diplayInsertCardImage()
   {
       jLabelImageScreen.repaint();
       jLabelImageScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cmu/sei/atm/resources/insertCardScreen.png")));
       jLabelImageScreen.setVisible(true);

   }

   public void clearInsertCardImage()
   {
       jLabelImageScreen.setVisible(false);
      
   }
      
   public void diplayRemoveCardImage()
   {
       jLabelImageScreen.repaint();
       jLabelImageScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cmu/sei/atm/resources/removeCardScreen.png")));
       jLabelImageScreen.setVisible(true);

   }

   public void clearRemoveCardImage()
   {
       jLabelImageScreen.setVisible(false);
   }

   public void diplayPutEnvelopeImage()
   {
       jLabelImageScreen.repaint();
       jLabelImageScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cmu/sei/atm/resources/DepositScreen.png")));
       jLabelImageScreen.setVisible(true);
   }

   public void clearPutEnvelopeImage()
   {
       jLabelImageScreen.setVisible(false);
   }

   public void diplayTakeMoneyImage()
   {
       jLabelImageScreen.repaint();
       jLabelImageScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cmu/sei/atm/resources/CashScreen.png")));
       jLabelImageScreen.setVisible(true);
   }

   public void clearTakeMoneyImage()
   {
       jLabelImageScreen.setVisible(false);
   }



   // display a dollar amount
   public void displayDollarAmount( double amount )
   {
    screen.append("$ "+amount);
       //System.out.printf( "$%,.2f", amount );
   } // end method displayDollarAmount
}

/**************************************************************************
 *  2009-2010 by SENOUCI hadj.
 *  Email: senoucihs@gmail.com
 *  this code is free which mean
 *  you can re-utilize it as you want
 *************************************************************************/